"use client";

import { ArrowUpRight, ArrowRight, Github, Linkedin, Mail, X, Sparkles, FileText, ExternalLink } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";

type Product = { name: string; tag: string; domain: string; role: string; duration: string; challenge: string; research: string; thinking: string; solution: string; impact: string; reflection: string; deck?: string; live?: string; accent: string };
const products: Product[] = [
  { name:"BookMyMentor", tag:"Make career learning feel credible before it feels convenient.", domain:"Product strategy", role:"Product strategist", duration:"Product Carnival - Live Project", challenge:"An EdTech & HR-Tech platform needed a grounded route to stronger experience, conversion, retention and positioning.", research:"Customer discovery with 20+ learners surfaced two high-intent groups: placement-focused students and time-constrained career switchers. A product audit showed the biggest opportunity was trust and conversion, not feature volume.", thinking:"I mapped pain points by urgency and business impact, then used RICE. A manual payment flow and unclear positioning earned P0 attention; weak trust signals and jobs browsing followed.", solution:"A focused career-platform narrative, clearer enrollment experience, trust-building proof, and improved opportunity discovery - sequenced with GTM and measurement rather than treated as isolated UI fixes.", impact:"Top 9 nationally. Defined activation, completion and placement metrics alongside the product recommendations.", reflection:"The work reinforced that the sharpest product move can be removing friction around a promise, rather than adding another feature.", deck:"/decks/BookMyMentor_ProductStrategy_ManmohanAdhikari.pdf", accent:"violet" },
  { name:"PMAF", tag:"Turn fragmented public data into territory decisions.", domain:"Analytics / Strategy", role:"Analytics & product lead", duration:"Trilytics 2026", challenge:"Sun Pharma needed a comparable district-level view of pharmaceutical opportunity across overall, chronic and acute therapy markets.", research:"I integrated five public sources - Census, NFHS-5, Rural Health Statistics, SECC and RBI - into 851 harmonized state-district records.", thinking:"53 engineered features were grouped into six intuitive pillars. Min-max normalization, therapy-specific weights and sanity checks made the scoring model explainable and repeatable.", solution:"PMAF: an interactive exploration layer with Overall, Chronic and Acute opportunity scores, rankings and territory-planning outputs.", impact:"851 records scored and ranked. Pune led Overall PMAF at 61.03; the model is modular so new releases can refresh the full pipeline.", reflection:"Good analytics needs to be legible to the decision-maker. The dashboard matters because it gives a framework a usable next step.", deck:"/decks/Team_TriX_Trilytics2026_Deck.pdf", accent:"blue" },
  { name:"MuseumX", tag:"Preserve heritage. Invite people back into it.", domain:"Product / Experience strategy", role:"Strategy consultant", duration:"MuseumX Case Competition", challenge:"Bharat Heritage Museum needed to become more visitor-centric, digitally connected and financially sustainable without losing its cultural purpose.", research:"The brief showed healthy physical visitation but passive experiences, weak repeat intent and low digital engagement. Younger visitors made up less than one-third of annual footfall.", thinking:"I used Engaged Heritage Visitors as a north-star measure, supported by RICE prioritization and an AARRR growth lens across before, during and after the visit.", solution:"A digital companion, AI kiosks, Bharat Heritage Quest, AR/VR storytelling, community programs and a membership-led revenue ecosystem - delivered in phases.", impact:"A 3-year roadmap targets 40%+ digital engagement, 35%+ repeat visit rate and 60%+ NPS. These are strategy targets, not reported outcomes.", reflection:"The best digital layer does not distract from culture; it gives every visitor a more personal way into it.", deck:"/decks/museum-x-deck.pdf", accent:"orange" },
  { name:"DAY-1NE", tag:"A calmer first day, every day.", domain:"Productivity", role:"Builder", duration:"Independent product", challenge:"Students need a single, approachable place to turn fragmented academic work into a next action.", research:"Everyday study friction shaped the scope: focus, planning, CGPA visibility and deadlines belong in one lightweight flow.", thinking:"Scope stayed intentionally narrow - ship the recurring decisions first, not a bloated student dashboard.", solution:"Focus Sessions, Study Planner, CGPA Calculator and Deadline Countdown, deployed through Streamlit and Netlify.", impact:"A live product that demonstrates end-to-end product scope and user-flow thinking.", reflection:"Shipping has its own clarity: a live product tests what a case study can only hypothesize.", live:"https://day1-ne.streamlit.app", accent:"lime" },
  { name:"ISM Pulse", tag:"Make the campus easier to navigate together.", domain:"Community", role:"Builder", duration:"Independent product", challenge:"Campus information and opportunities are easy to miss when they live across disconnected student channels.", research:"The product begins with discoverability: what needs a shared surface, and what needs a safe, simple path to action.", thinking:"Information architecture came before features - the navigation had to make campus resources feel findable, not louder.", solution:"A centralized campus platform featuring confessions and a marketplace, built with HTML, CSS, JavaScript and Firebase.", impact:"A live community product built around campus resource discovery.", reflection:"Community products succeed or fail on the clarity and safety of their everyday interactions.", live:"https://ism-pulse.netlify.app", accent:"rose" }
];

const askMannKnowledge = [
  { keys:["who are you","about you","tell me about mann","manmohan"], reply:"Mann is Manmohan Adhikari - a product-minded builder studying Chemical Engineering at IIT (ISM) Dhanbad. He works across product research, strategy, analytics and shipped student products." },
  { keys:["education","iit","college","study"], reply:"Manmohan is pursuing B.Tech in Chemical Engineering at IIT (ISM) Dhanbad, with an expected 2029 graduation and an 8.81/10 CGPA on the supplied résumé." },
  { keys:["skills","tools","tech stack","technology"], reply:"His toolkit spans Python, SQL, C/C++, HTML/CSS, Firebase, Streamlit, GitHub, Figma and Netlify - with product strengths in customer discovery, user research, RICE, GTM, roadmapping and wireframing." },
  { keys:["bookmymentor","book my mentor","mentor"], reply:"BookMyMentor started with discovery across 20+ learners and a product audit. The key insight was that trust and conversion gaps mattered more than missing features; the work placed Top 9 nationally." },
  { keys:["pmaf","trilytics","sun pharma","pharmaceutical"], reply:"PMAF harmonized five public datasets into 53 features across six pillars, producing Overall, Chronic and Acute district opportunity scores for pharmaceutical market prioritization." },
  { keys:["museum","museumx","heritage"], reply:"MuseumX uses Engaged Heritage Visitors as its north-star metric, connecting a more personal museum experience to repeat visits, digital engagement and sustainable revenue." },
  { keys:["day-1ne","day 1","productivity"], reply:"DAY-1NE is a student productivity product with Focus Sessions, a Study Planner, CGPA Calculator and Deadline Countdown. It was deliberately scoped around recurring student decisions." },
  { keys:["ism pulse","campus","community"], reply:"ISM Pulse is a centralized campus product with confessions and a marketplace. Its product thinking began with information architecture - making campus resources easier to find and act on." },
  { keys:["photography","framed echoes","framedechoes","photos"], reply:"FramedEchoes is Mann's photography brand. It is a practice in noticing: movement in a Dhanbad morning, a road under the moon, or the meeting of past and present in Jaipur." },
  { keys:["prioritize","rice","prioritization"], reply:"Mann uses prioritization to make trade-offs explicit. In BookMyMentor, RICE put manual payment friction and unclear positioning at P0 before lower-leverage additions." },
  { keys:["philosophy","how do you build","thinking","approach"], reply:"The philosophy is simple: understand the problem, make the decision legible, then build the smallest meaningful experience. The website tells the story before showing supporting evidence." },
  { keys:["resume","experience","linkedin","github"], reply:"You can open Mann's résumé from the navigation or footer. LinkedIn and GitHub are also linked there for a faster recruiter path." }
];

function ProductModal({ product, close }: { product: Product; close: () => void }) {
  return <div className="modal-backdrop" onClick={close}>
    <article className="case" onClick={e=>e.stopPropagation()}>
      <button className="close" onClick={close} aria-label="Close case study"><X size={18}/></button>
      <span className="eyebrow">{product.domain} / {product.duration}</span><h2>{product.name}</h2><p className="case-tag">{product.tag}</p>
      <div className="case-meta"><span>Role<br/><b>{product.role}</b></span><span>Format<br/><b>{product.duration}</b></span></div>
      {[["The Challenge",product.challenge],["Research",product.research],["Thinking",product.thinking],["Final Solution",product.solution],["Business Impact",product.impact],["Reflection",product.reflection]].map(([title,copy],i)=><section className="case-section" key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{copy}</p></div></section>)}
      <div className="case-actions">{product.deck && <a href={product.deck} target="_blank"><FileText size={16}/> View complete deck</a>}{product.live && <a href={product.live} target="_blank"><ExternalLink size={16}/> Open platform</a>}</div>
    </article></div>
}

export default function Home() {
  const [loading,setLoading]=useState(true); const [selected,setSelected]=useState<Product|null>(null); const [question,setQuestion]=useState(""); const [answer,setAnswer]=useState("Ask about a project, my process, or the way I build."); const [cursor,setCursor]=useState({x:-200,y:-200});
  useEffect(()=>{const t=setTimeout(()=>setLoading(false),1100); return ()=>clearTimeout(t)},[]);
  useEffect(()=>{const move=(e:MouseEvent)=>setCursor({x:e.clientX,y:e.clientY}); window.addEventListener("mousemove",move); return()=>window.removeEventListener("mousemove",move)},[]);
  const ask=(e:FormEvent)=>{e.preventDefault(); const q=question.toLowerCase(); if(!q.trim()) return; const match=askMannKnowledge.find(item=>item.keys.some(key=>q.includes(key))); setAnswer(match?.reply ?? "I can help with Mann's projects, résumé, skills, photography and product philosophy. Try asking about PMAF, BookMyMentor, DAY-1NE, ISM Pulse, MuseumX, FramedEchoes or product thinking."); setQuestion(""); };
  if(loading) return <main className="loader"><div>MANN<span>.</span></div></main>;
  return <main><i className="cursor-glow" style={{transform:`translate(${cursor.x}px, ${cursor.y}px)`}}/>
    <div className="noise"/><header><a href="#top" className="wordmark">MANN<span>.</span></a><nav><a href="#meet">Meet Mann</a><a href="#products">Products</a><a href="#lens">Through My Lens</a><a href="#ask">Ask Mann</a></nav><a className="resume-link" href="/resume/Manmohan_Adhikari_Resume.pdf" target="_blank">Résumé <ArrowUpRight size={15}/></a></header>
    <section id="top" className="hero"><p>MANMOHAN ADHIKARI / PRODUCT, BUILT WITH INTENT</p><h1>MANN<span>.</span></h1><div className="hero-bottom"><p>I build things that excite me.</p><a href="#products">Explore the work <ArrowRight size={16}/></a></div></section>
    <section id="meet" className="meet section"><span className="eyebrow">01 / MEET MANN</span><div><h2>Curious by default.<br/>Deliberate by practice.</h2><p>I’m Manmohan Adhikari - a product-minded builder studying Chemical Engineering at IIT (ISM) Dhanbad. I enjoy turning ambiguous problems into experiences, systems and decisions people can actually use.</p><div className="quick-links"><a href="https://linkedin.com/in/adhikarimann" target="_blank"><Linkedin/> LinkedIn</a><a href="https://github.com/adhikarimann" target="_blank"><Github/> GitHub</a><a href="mailto:adhikarimann27@gmail.com"><Mail/> Email</a></div></div></section>
    <section id="products" className="products section"><div className="section-title"><span className="eyebrow">02 / PRODUCTS</span><h2>The work behind<br/>the point of view.</h2><p>Each one starts with the problem, not the presentation.</p></div><div className="product-grid">{products.map((p,i)=><button className={`product-card ${p.accent}`} key={p.name} onClick={()=>setSelected(p)}><span>0{i+1}</span><div><small>{p.domain}</small><h3>{p.name}</h3><p>{p.tag}</p></div><ArrowUpRight/></button>)}</div></section>
    <section id="lens" className="lens section"><div className="section-title"><span className="eyebrow">03 / THROUGH MY LENS</span><h2>Frames that make<br/>me pause.</h2><p>FramedEchoes is where attention becomes a photograph.</p><a href="https://framedechoes.netlify.app" target="_blank" className="text-link">Visit FramedEchoes <ArrowUpRight size={16}/></a></div><div className="photo-grid"><figure className="photo p1"><img src="/photography/attendance-present.jpg" alt="Two schoolboys riding a scooter through Dhanbad"/><span>01 / DHANBAD</span><figcaption>Attendance: Present. Helmet: Absent.</figcaption></figure><figure className="photo p2"><img src="/photography/watching-moon.jpg" alt="Headlights moving below a moonlit road in Jamtara"/><span>02 / JAMTARA</span><figcaption>Under a Watching Moon.</figcaption></figure><figure className="photo p3"><img src="/photography/two-timelines.jpg" alt="A visitor using a phone in Jaipur's historic architecture"/><span>03 / JAIPUR</span><figcaption>Two Timelines.</figcaption></figure></div></section>
    <section id="ask" className="ask section"><div><span className="eyebrow">04 / ASK MANN</span><h2>Start with a<br/>good question.</h2><p>A small, focused guide to the work, the methods and the lens behind it.</p></div><form onSubmit={ask}><div className="orb"><Sparkles size={18}/></div><p className="answer">{answer}</p><div className="ask-row"><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What did you learn from PMAF?" aria-label="Ask Mann"/><button aria-label="Send question"><ArrowUpRight/></button></div><small>Ask Mann only knows Mann's work, résumé, skills, photography and product philosophy.</small></form></section>
    <footer><div><a className="wordmark" href="#top">MANN<span>.</span></a><p>Build something worth remembering.</p></div><div><a href="/resume/Manmohan_Adhikari_Resume.pdf" target="_blank">Résumé</a><a href="https://linkedin.com/in/adhikarimann" target="_blank">LinkedIn</a><a href="https://github.com/adhikarimann" target="_blank">GitHub</a></div><small>© 2026 Manmohan Adhikari</small></footer>
    {selected && <ProductModal product={selected} close={()=>setSelected(null)}/>} 
  </main>
}
