export type Project = {
  slug: string;
  name: string;
  tag: string;
  domain: string;
  role: string;
  duration: string;
  challenge: string;
  research: string;
  thinking: string;
  solution: string;
  impact: string;
  reflection: string;
  deck?: string;
  live?: string;
};

export const projects: Project[] = [
  { slug:"book-my-mentor", name:"BookMyMentor", tag:"Make career learning feel credible before it feels convenient.", domain:"Product strategy", role:"Product strategist", duration:"Product Carnival - Live Project", challenge:"An EdTech & HR-Tech platform needed a grounded route to stronger experience, conversion, retention and positioning.", research:"Customer discovery with 20+ learners surfaced two high-intent groups: placement-focused students and time-constrained career switchers. A product audit showed the biggest opportunity was trust and conversion, not feature volume.", thinking:"I mapped pain points by urgency and business impact, then used RICE. A manual payment flow and unclear positioning earned P0 attention; weak trust signals and jobs browsing followed.", solution:"A focused career-platform narrative, clearer enrollment experience, trust-building proof, and improved opportunity discovery - sequenced with GTM and measurement rather than treated as isolated UI fixes.", impact:"Top 9 nationally. Defined activation, completion and placement metrics alongside the product recommendations.", reflection:"The work reinforced that the sharpest product move can be removing friction around a promise, rather than adding another feature.", deck:"/decks/BookMyMentor_ProductStrategy_ManmohanAdhikari.pdf" },
  { slug:"pmaf", name:"PMAF", tag:"Turn fragmented public data into territory decisions.", domain:"Analytics / Strategy", role:"Analytics & product lead", duration:"Trilytics 2026", challenge:"Sun Pharma needed a comparable district-level view of pharmaceutical opportunity across overall, chronic and acute therapy markets.", research:"I integrated five public sources - Census, NFHS-5, Rural Health Statistics, SECC and RBI - into 851 harmonized state-district records.", thinking:"53 engineered features were grouped into six intuitive pillars. Min-max normalization, therapy-specific weights and sanity checks made the scoring model explainable and repeatable.", solution:"PMAF: an interactive exploration layer with Overall, Chronic and Acute opportunity scores, rankings and territory-planning outputs.", impact:"851 records scored and ranked. Pune led Overall PMAF at 61.03; the model is modular so new releases can refresh the full pipeline.", reflection:"Good analytics needs to be legible to the decision-maker. The dashboard matters because it gives a framework a usable next step.", deck:"/decks/Team_TriX_Trilytics2026_Deck.pdf" },
  { slug:"museumx", name:"MuseumX", tag:"Preserve heritage. Invite people back into it.", domain:"Product / Experience strategy", role:"Strategy consultant", duration:"MuseumX Case Competition", challenge:"Bharat Heritage Museum needed to become more visitor-centric, digitally connected and financially sustainable without losing its cultural purpose.", research:"The brief showed healthy physical visitation but passive experiences, weak repeat intent and low digital engagement. Younger visitors made up less than one-third of annual footfall.", thinking:"I used Engaged Heritage Visitors as a north-star measure, supported by RICE prioritization and an AARRR growth lens across before, during and after the visit.", solution:"A digital companion, AI kiosks, Bharat Heritage Quest, AR/VR storytelling, community programs and a membership-led revenue ecosystem - delivered in phases.", impact:"A 3-year roadmap targets 40%+ digital engagement, 35%+ repeat visit rate and 60%+ NPS. These are strategy targets, not reported outcomes.", reflection:"The best digital layer does not distract from culture; it gives every visitor a more personal way into it.", deck:"/decks/museum-x-deck.pdf" },
  { slug:"day-1ne", name:"DAY-1NE", tag:"A calmer first day, every day.", domain:"Productivity", role:"Builder", duration:"Independent product", challenge:"Students need a single, approachable place to turn fragmented academic work into a next action.", research:"Everyday study friction shaped the scope: focus, planning, CGPA visibility and deadlines belong in one lightweight flow.", thinking:"Scope stayed intentionally narrow - ship the recurring decisions first, not a bloated student dashboard.", solution:"Focus Sessions, Study Planner, CGPA Calculator and Deadline Countdown, deployed through Streamlit and Netlify.", impact:"A live product that demonstrates end-to-end product scope and user-flow thinking.", reflection:"Shipping has its own clarity: a live product tests what a case study can only hypothesize.", live:"https://day1-ne.streamlit.app" },
  { slug:"ism-pulse", name:"ISM Pulse", tag:"Make the campus easier to navigate together.", domain:"Community", role:"Builder", duration:"Independent product", challenge:"Campus information and opportunities are easy to miss when they live across disconnected student channels.", research:"The product begins with discoverability: what needs a shared surface, and what needs a safe, simple path to action.", thinking:"Information architecture came before features - the navigation had to make campus resources feel findable, not louder.", solution:"A centralized campus platform featuring confessions and a marketplace, built with HTML, CSS, JavaScript and Firebase.", impact:"A live community product built around campus resource discovery.", reflection:"Community products succeed or fail on the clarity and safety of their everyday interactions.", live:"https://ism-pulse.netlify.app" }
];

export function findProject(slug: string) {
  return projects.find((project) => project.slug === slug);
}
